import { IRoute } from "@bluelibs/x-ui";
import "./i18n";

import {
  END_USER_BOOK_TESTS_LIST as BASE_END_USER_BOOK_TESTS_LIST,
  END_USER_BOOK_TESTS_CREATE as BASE_END_USER_BOOK_TESTS_CREATE,
  END_USER_BOOK_TESTS_EDIT as BASE_END_USER_BOOK_TESTS_EDIT,
  END_USER_BOOK_TESTS_VIEW as BASE_END_USER_BOOK_TESTS_VIEW,
} from "./config/routes";

export const END_USER_BOOK_TESTS_LIST: IRoute = {
  ...BASE_END_USER_BOOK_TESTS_LIST,
};

export const END_USER_BOOK_TESTS_CREATE: IRoute = {
  ...BASE_END_USER_BOOK_TESTS_CREATE,
};

export const END_USER_BOOK_TESTS_EDIT: IRoute = {
  ...BASE_END_USER_BOOK_TESTS_EDIT,
};

export const END_USER_BOOK_TESTS_VIEW: IRoute = {
  ...BASE_END_USER_BOOK_TESTS_VIEW,
};
